spring.application.name=duanjava6

# Cấu hình kết nối database SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=asmjv6;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# Cấu hình ViewResolver cho JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngsanhtai10688@gmail.com
spring.mail.password=ofwjgfdqkvbirszu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
